name: simplegit
description: Simple wrapper around libgit2 for Dart
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  ffi: ^2.1.0
  option_result: ^3.2.1

dev_dependencies:
  ffigen: ^11.0.0
  lints: ^5.0.0
  test: ^1.24.0

ffigen:
  name: GitSys
  description: Bindings for libgit2
  output: lib/src/bindings/simplegit.dart
  headers:
    entry-points:
      - 'build-linux/install/include/git2.h'
  compiler-opts:
    - '-Ibuild-linux/install/include'
